### PR TITLE
Upgrade bevy to 0.11 and iced to 0.10

### PR DESCRIPTION
**Pull request by jsatka**
Currently all iced crate dependencies have to point to a recent master branch revision until version 0.10 is released with wgpu version 0.16, on which bevy 0.11 depens on.

Tested that all checks pass on Ubuntu and all three examples run as expected.

### CODE REVIEW

**Comment by jsatka** [comment]
I am not yet sure if more iced sub-crate types would need to be re-exported with `pub` in order to utilize all features of iced. Any thoughts are welcome.

**Comment by tasgon** [comment]
If you don't mind, why did you decide to add the `fonts` example?

**Comment by EmperialDev** [comment]
I actually think it's a good idea to have a font example, it took me a long time to find out how to use a font with bevy_iced and iced 0.9, and I actually thougt it was nearly impossible to do so on iced 0.10. So I think ist's a great help to beginners.

**Comment by jsatka** [comment]
> If you don't mind, why did you decide to add the `fonts` example?

Sure! Happy to discuss any other changes, too, if there's anything that doesn't seem like an obvious choice to other collaborators or users.

I thought it may not be obvious, with beginners in mind as @EmperialDev pointed out, how to include own fonts because they have to be included as static byte arrays, which differs from Bevy's native UI primary way of loading fonts via the `AssetServer`. Therefore I believed it could be a time-saver for some beginners.

**Comment by tasgon** [comment]
Thinking about it more, I see the rationality, but I think we should instead create a custom asset loader for iced fonts instead of having to statically include them into the binary. That way, multiple assets can be used without making the binary balloon into massive sizes and it gives game developers the option of allowing user-replaceable fonts. What do you think?

**Comment by jsatka** [comment]
Custom asset loader would be great, if not essential, for image assets and I am all for it!

But with fonts only I'd think that static inclusion would be enough for a vast majority of game developers. On one hand, I have a hard time thinking about a game where it'd be necessary or useful for players to be able to play around with the fonts. But on the other hand, I know Bevy can be and is being used to develop other kinds of apps, too, so the added flexibility wouldn't hurt.

**Comment by tasgon** [comment]
> I have a hard time thinking about a game where it'd be necessary or useful for players to be able to play around with the fonts.

Games that support custom skins/texture packs come to mind, such as Minecraft or TF2. Looking at the code, though, it might be a bit annoying, so I'll probably just accept this as-is, but I will change the example to instead load the font from a file at start time rather than statically including it into the binary.

**Comment by tadeohepperle** [comment]
Hey guys, I would be very thankful if we could get this merged into the master branch soon :)

**Pull request merged**
