### PR TITLE
Push iced wgpu features, to make possible enable image support and more useful features

### PR DESCRIPTION
**Pull request by silvestrpredko**
…re useful features

### CODE REVIEW

**Comment by silvestrpredko** [comment]
I don't know why, but with `svg` feature, it has a lot of `clippy` issues, so I just remove that feature.

**Comment by tasgon** [comment]
If you don't mind, why are you force-pushing over your previous commits? It would be nice to see the exact issues you're getting from clippy.

**Comment by silvestrpredko** [comment]
@tasgon With force-pushing I am trying to keep the commit history clean. Unfortunately, I don't know the other way how to accomplish this task. To get output for `svg` please add  `svg` feature. Like this:
```Toml
svg = ["iced_wgpu/svg"]
```

**Comment by tasgon** [comment]
Don't worry about keeping the commit history squeaky clean. I can always squash and merge if I feel it's a problem.

I've been busy this week, so sorry for the sporadic communication, but I'll try to take a look at the svg issue today.

**Pull request closed without merging**
